name: Cloud Assignment (Student Repository)

concurrency:
  group: cloud
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      assignment:
        description: 'Name of the assignment e.g. spamoverflow'
        required: true
        type: string
      deploy:
        description: 'Deploy the terraform'
        required: false
        type: boolean
        default: false
      deployed-url:
        description: 'URL of the deployed instance iff deploy is false'
        required: false
        type: string
      functionality:
        description: 'Run functionality tests against the deployment'
        required: false
        type: boolean
        default: false
      load:
        description: 'Run sample load tests against the deployment'
        required: false
        type: boolean
        default: false
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: false
        type: string
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: false
        type: string
      aws-session-token:
        description: 'AWS Session Token'
        required: false
        type: string

jobs:
  deploy-local:
    name: Build & Test (Stage 1)
    if: ${{ github.ref_name == 'stage-1' || startsWith(github.ref_name, 'stage-1/') }}
    runs-on: [self-hosted, Linux, X64, amazon, student]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.12'

      - name: Build
        shell: bash
        timeout-minutes: 20
        run: |
          chmod +x local.sh
          ./local.sh

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CLOUD_ASSIGNMENT_APP_ID }}
          private-key: ${{ secrets.CLOUD_ASSIGNMENT_PRIVATE_KEY }}
          owner: CSSE6400
          repositories: |
            ${{ inputs.assignment }}-tests
      
      - name: Clone tests
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: csse6400/${{ inputs.assignment }}-tests
          path: marking

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        shell: bash
        run: |
          cd marking && poetry install

      - name: Warning
        shell: bash
        run: |
          echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
          echo "> The functionality tests provide feedback on your solution but are not your grade for the stage." >> $GITHUB_STEP_SUMMARY

      - name: Run tests
        shell: bash
        env:
          pytest_github_report: true
          pytest_report_title: ":stethoscope: Functionality Tests"
          pytest_verbosity: 2
        run: |
          echo "running tests...."
          cd marking && poetry run pytest functionality --timeout 15

  deploy-remote:
    name: Build & Deploy (Stage 2/3)
    if: ${{ inputs.deploy && (github.ref_name == 'stage-2' || startsWith(github.ref_name, 'stage-2/') || github.ref_name == 'stage-3' || startsWith(github.ref_name, 'stage-3/')) }}
    runs-on: [self-hosted, Linux, X64, amazon, student]
    outputs:
      endpoint: ${{ steps.collect.outputs.endpoint }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check
        uses: actions/github-script@v8
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ inputs.aws-session-token }}
        with:
          script: |
            const awsAccessKeyID = process.env.AWS_ACCESS_KEY_ID;
            const awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
            const awsSessionToken = process.env.AWS_SESSION_TOKEN;
            
            if (awsAccessKeyID === undefined || awsAccessKeyID == '' || awsSecretAccessKey === undefined || awsSecretAccessKey == '' || awsSessionToken === undefined || awsSessionToken == '') {
              await core.summary.addRaw(`
              > [!CAUTION]
              > AWS credentials were not provided to the workflow
                `).write();    
              core.setFailed('AWS Credentials have not been provided');
            }
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-session-token: ${{ inputs.aws-session-token }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: fmt check
        id: fmt
        run: terraform fmt -check

      - name: Execute before script if it exists
        run: |
          SCRIPT_PATH="./before.sh"
          if [ -f "$SCRIPT_PATH" ]; then
            echo "::notice file=$SCRIPT_PATH::Script found, executing."
            # Make the script executable and run it
            chmod +x "$SCRIPT_PATH"
            ./before.sh
          else
            echo "::warning file=$SCRIPT_PATH::Script not found, skipping execution."
          fi
        shell: bash

      - name: Init
        run: terraform init

      - name: Plan
        env:
          TF_AWS_DEFAULT_TAGS_Course: CSSE6400
          TF_AWS_DEFAULT_TAGS_CourseRole: Student
        run: |
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - uses: borchero/terraform-plan-comment@v2
        with:
          token: "${{ github.token }}"
          planfile: "tfplan.binary"
          header: 📝 Terraform Plan
          skip-comment: true

      - name: Upload terraform plan (json)
        uses: actions/upload-artifact@v6
        with:
          name: tfplan.json
          path: tfplan.json

      - name: Apply
        env:
          TF_AWS_DEFAULT_TAGS_Course: CSSE6400
          TF_AWS_DEFAULT_TAGS_CourseRole: Student
        run: terraform apply -auto-approve
      
      - name: Upload terraform state
        uses: actions/upload-artifact@v6
        with:
          name: terraform.tfstate
          path: terraform.tfstate

      - name: Collect deployed URL
        id: collect
        shell: bash
        run: |
          echo "endpoint=$(terraform output -raw api)" >> "$GITHUB_OUTPUT"
      
      - name: Sleep for 10 minutes
        shell: bash
        run: |
          echo 'Sleeping for 10 minutes to allow resources to warmup...'
          sleep 10m

  deploy-external:
    name: Deployed External (via user) (Stage 2 & 3)
    if: ${{ inputs.deploy != true && inputs.deployed-url != '' && (github.ref_name == 'stage-2' || startsWith(github.ref_name, 'stage-2/') || github.ref_name == 'stage-3' || startsWith(github.ref_name, 'stage-3/')) }}
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    outputs:
      endpoint: ${{ steps.collect.outputs.endpoint }}
    steps:
      - name: Collect deployed URL
        shell: bash
        id: collect
        run: |
          echo "endpoint=${{ inputs.deployed-url }}" >> "$GITHUB_OUTPUT"

  deploy-check:
    name: Check Endpoint (Stage 2 & 3)
    if: ${{ always() && (inputs.deploy || inputs.deployed-url != '' || inputs.functionality ) && (github.ref_name == 'stage-2' || startsWith(github.ref_name, 'stage-2/') || github.ref_name == 'stage-3' || startsWith(github.ref_name, 'stage-3/')) }}
    needs: [deploy-remote, deploy-external]
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    outputs:
      endpoint: ${{ steps.check.outputs.endpoint }}
    steps:
      - name: Check
        id: check
        uses: actions/github-script@v8
        env:
          ENDPOINT_REMOTE: ${{ needs.deploy-remote.outputs.endpoint }}
          ENDPOINT_EXTERNAL: ${{ needs.deploy-external.outputs.endpoint }}
        with:
          script: |
            const remote = process.env.ENDPOINT_REMOTE;
            const external = process.env.ENDPOINT_EXTERNAL;
            
            console.log('remote (' + remote + ') external (' + external + ')');
            
            const endpoint = remote || external;
            if (endpoint === undefined || endpoint == '' ) {
              core.setFailed('Do not have a valid test endpoint');
            }
            
            // todo: check that the endpoint is a correct url
            
            console.log('Test Endpoint: ' + endpoint);
            core.setOutput('endpoint', endpoint);

  functionality:
    name: Test Functionality
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    if: ${{ always() && inputs.functionality && (github.ref_name == 'stage-2' || startsWith(github.ref_name, 'stage-2/') || github.ref_name == 'stage-3' || startsWith(github.ref_name, 'stage-3/')) }}
    needs: [deploy-check]
    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check
        uses: actions/github-script@v8
        env:
          TEST_HOST: ${{ needs.deploy-check.outputs.endpoint }}
        with:
          script: |
            const endpoint = process.env.TEST_HOST;
            
            if (endpoint === undefined || endpoint == '' ) {
              core.setFailed('Do not have a valid test endpoint');
            }

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.12'

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CLOUD_ASSIGNMENT_APP_ID }}
          private-key: ${{ secrets.CLOUD_ASSIGNMENT_PRIVATE_KEY }}
          owner: CSSE6400
          repositories: |
            ${{ inputs.assignment }}-tests
      
      - name: Clone tests
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: csse6400/${{ inputs.assignment }}-tests
          path: marking

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        shell: bash
        run: |
          cd marking && poetry install

      - name: Warning
        shell: bash
        run: |
          echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
          echo "> The functionality tests provide feedback on your solution but are not your grade for the stage." >> $GITHUB_STEP_SUMMARY

      - name: Run tests
        shell: bash
        env:
          pytest_github_report: true
          pytest_report_title: ":stethoscope: Functionality Tests"
          pytest_verbosity: 2
          TEST_HOST: ${{ needs.deploy-check.outputs.endpoint }}
        run: |
          echo "running tests...."
          cd marking && poetry run pytest functionality

  load:
    name: Test Scalability
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    if: ${{ always() && inputs.load && github.ref_name == 'stage-3' }}
    needs: [deploy-check, functionality]
    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check
        uses: actions/github-script@v8
        env:
          TEST_HOST: ${{ needs.deploy-check.outputs.endpoint }}
        with:
          script: |
            const endpoint = process.env.TEST_HOST;
            
            if (endpoint === undefined || endpoint == '' ) {
              core.setFailed('Do not have a valid test endpoint');
            }

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CLOUD_ASSIGNMENT_APP_ID }}
          private-key: ${{ secrets.CLOUD_ASSIGNMENT_PRIVATE_KEY }}
          owner: CSSE6400
          repositories: |
            ${{ inputs.assignment }}-tests
      
      - name: Clone tests
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: csse6400/${{ inputs.assignment }}-tests
          ref: wip
          path: marking
      
      - name: Install K6
        uses: grafana/setup-k6-action@v1

      - name: Warning
        shell: bash
        run: |
          echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
          echo "> The load tests provide feedback on your solution but are not your grade for the stage." >> $GITHUB_STEP_SUMMARY

      - name: Install dependencies
        shell: bash
        env:
          K6_SUMMARY_MODE: compact
          TEST_HOST: ${{ needs.deploy-check.outputs.endpoint }}
        run: |
          cd marking/scalability && ./run.sh >> $GITHUB_STEP_SUMMARY

  deploy-destroy:
    name: Destroy (Stage 2/3)
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    if: ${{ always() && inputs.deploy && (github.ref_name == 'stage-2' || startsWith(github.ref_name, 'stage-2/') || github.ref_name == 'stage-3' || startsWith(github.ref_name, 'stage-3/')) }}
    needs: [deploy-remote, functionality, load]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check
        uses: actions/github-script@v8
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ inputs.aws-session-token }}
        with:
          script: |
            const awsAccessKeyID = process.env.AWS_ACCESS_KEY_ID;
            const awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
            const awsSessionToken = process.env.AWS_SESSION_TOKEN;
            
            if (awsAccessKeyID === undefined || awsAccessKeyID == '' || awsSecretAccessKey === undefined || awsSecretAccessKey == '' || awsSessionToken === undefined || awsSessionToken == '') {
              await core.summary.addRaw(`
              > [!CAUTION]
              > AWS credentials were not provided to the workflow
                `).write();  
              core.setFailed('AWS Credentials have not been provided');
            }
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-session-token: ${{ inputs.aws-session-token }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Get State
        uses: actions/download-artifact@v8
        with:
          name: terraform.tfstate

      - name: Init
        run: terraform init

      - name: Plan
        run: |
          terraform plan -destroy -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - uses: borchero/terraform-plan-comment@v2
        with:
          token: "${{ github.token }}"
          planfile: "tfplan.binary"
          header: 📝 Terraform Plan (Destroy)
          skip-comment: true

      - name: Destroy
        run: terraform destroy -auto-approve
