name: Cloud Assignment (Student Repository)

concurrency:
  group: cloud
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      assignment:
        description: 'Name of the assignment e.g. spamoverflow'
        required: true
        type: string
      deploy:
        description: 'Deploy the terraform'
        required: false
        type: boolean
        default: false
      deployed-url:
        description: 'URL of the deployed instance iff deploy is false'
        required: false
        type: string
      functionality:
        description: 'Run functionality tests against the deployment'
        required: false
        type: boolean
        default: false
      load:
        description: 'Run sample load tests against the deployment'
        required: false
        type: boolean
        default: false
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: false
        type: string
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: false
        type: string
      aws-session-token:
        description: 'AWS Session Token'
        required: false
        type: string

jobs:
  deploy-local:
    name: Build & Test (Stage 1)
    if: ${{ github.ref_name == 'stage-1' || startsWith(github.ref_name, 'stage-1/') }}
    runs-on: [self-hosted, Linux, X64, amazon, student]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.12'

      - name: Build
        shell: bash
        timeout-minutes: 20
        run: |
          chmod +x local.sh
          ./local.sh

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CLOUD_ASSIGNMENT_APP_ID }}
          private-key: ${{ secrets.CLOUD_ASSIGNMENT_PRIVATE_KEY }}
          owner: CSSE6400
          repositories: |
            ${{ inputs.assignment }}-tests
      
      - name: Clone tests
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: csse6400/${{ inputs.assignment }}-tests
          path: marking

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        shell: bash
        run: |
          cd marking && poetry install

      - name: Warning
        shell: bash
        run: |
          echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
          echo "> The functionality tests provide feedback on your solution but are not your grade for the stage." >> $GITHUB_STEP_SUMMARY

      - name: Run tests
        shell: bash
        env:
          pytest_github_report: true
          pytest_report_title: ":stethoscope: Functionality Tests"
          pytest_verbosity: 2
        run: |
          echo "running tests...."
          cd marking && poetry run pytest functionality

  deploy-remote:
    name: Build & Deploy (Stage 2/3)
    if: ${{ inputs.deploy && (github.ref_name == 'stage-2' || startsWith(github.ref_name, 'stage-2/') || github.ref_name == 'stage-3' || startsWith(github.ref_name, 'stage-3/')) }}
    runs-on: [self-hosted, Linux, X64, amazon, student]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-session-token: ${{ inputs.aws-session-token }}
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: fmt check
        id: fmt
        run: terraform fmt -check

      - name: Execute before script if it exists
        run: |
          SCRIPT_PATH="./before.sh"
          if [ -f "$SCRIPT_PATH" ]; then
            echo "::notice file=$SCRIPT_PATH::Script found, executing."
            # Make the script executable and run it
            chmod +x "$SCRIPT_PATH"
            ./before.sh
          else
            echo "::warning file=$SCRIPT_PATH::Script not found, skipping execution."
          fi
        shell: bash

      - name: Init
        run: terraform init

      - name: Plan
        run: |
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - uses: borchero/terraform-plan-comment@v2
        with:
          token: "${{ github.token }}"
          planfile: "tfplan.binary"
          header: 📝 Terraform Plan
          skip-comment: true

      - name: Upload terraform plan (json)
        uses: actions/upload-artifact@v4
        with:
          name: tfplan.json
          path: tfplan.json

      - name: Apply
        run: terraform apply -auto-approve
      
      - name: Upload terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform.tfstate
          path: terraform.tfstate
