name: Cloud Assignment [Stage 1]

on:
  workflow_call:
    inputs:
      assignment:
        description: 'Name of the assignment e.g. spamoverflow'
        required: true
        type: string
      repository:
        description: 'Name of the respository to run'
        required: true
        type: string
      commit:
        description: 'Commit hash to checkout'
        required: true
        type: string

jobs:
  mark:
    name: Stage 1 Mark
    runs-on: [self-hosted, Linux, X64, amazon, student]
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.CLOUD_ASSIGNMENT_MARKING_APP_ID }}
          private-key: ${{ secrets.CLOUD_ASSIGNMENT_MARKING_PRIVATE_KEY }}
          owner: CSSE6400
          repositories: |
            ${{ inputs.assignment }}-tests
            ${{ inputs.assignment }}-${{ inputs.repository }}

      - name: Checkout student code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: csse6400/${{ inputs.assignment }}-${{ inputs.repository }}
          ref: ${{ inputs.commit }}
          path: submission

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.12'

      - name: Build
        shell: bash
        timeout-minutes: 10
        run: |
          cd submission
          chmod +x local.sh
          ./local.sh
      
      - name: Clone tests
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: csse6400/${{ inputs.assignment }}-tests
          path: marking

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        shell: bash
        run: |
          cd marking && poetry install

      - name: Run tests
        shell: bash
        env:
          pytest_github_report: true
          pytest_report_title: ":stethoscope: Functionality Tests"
          pytest_verbosity: 1
        run: |
          echo "running tests...."
          cd marking && poetry run pytest functionality --timeout 15 --junit-xml=report.xml
      
      - name: Upload test report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: report.xml
          path: marking/report.xml