name: Linting (optional)

on:
  workflow_call:

jobs:
  invalid:
    name: Invalid Branch Check
    if: ${{ !(github.ref_name == 'stage-1' || github.ref_name == 'stage-2' || github.ref_name == 'stage-3') }}
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Invalid Branch Check
        shell: bash
        run: |
          echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
          echo "> This is not a valid branch and this will not be credited as a submission." >> $GITHUB_STEP_SUMMARY
          exit 1

  local:
    if: ${{ github.ref_name == 'stage-1' }}
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check for docker cli usage in local.sh
        shell: bash
        run: |
            FILE_LOCAL="local.sh"
            if ! grep -q "docker" "$FILE_LOCAL"; then
              echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
              echo "> No docker usage detected in local.sh, see spec section 4.1: 'The local.sh script must launch your container with port 8080'" >> $GITHUB_STEP_SUMMARY
            fi

  terraform:
    if: ${{ github.ref_name == 'stage-2' || github.ref_name == 'stage-3' }}
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: fmt check
        id: fmt
        run: terraform fmt -check

      - name: Init
        run: terraform init

      - name: Validate
        id: validate
        run: terraform validate

      - name: TFLint config
        id: tflint-config
        run: |
          cat <<EOF > .tflint.hcl
          tflint {
            required_version = ">= 0.50"
          }
            
          config {
            format = "compact"
          }

          plugin "terraform" {
            enabled = true
            preset  = "recommended"
          }

          plugin "opa" {
            enabled = true
            version = "0.10.0"
            source  = "github.com/terraform-linters/tflint-ruleset-opa"
          }

          rule "terraform_required_version" {
            enabled = false
          }

          rule "terraform_naming_convention" {
            enabled = true
          }

          EOF

      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact


  ai:
    name: AI
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Document AI usage
        shell: bash
        run: |
            FILE_AI="AI.md"
            if [ -f "$FILE_AI" ]; then
              echo "# AI Declaration" >> $GITHUB_STEP_SUMMARY
              cat "$FILE_AI" >> $GITHUB_STEP_SUMMARY
            else 
              echo "> [!IMPORTANT]" >> $GITHUB_STEP_SUMMARY
              echo "> No AI usage declared or declaration is missing. If you did not use AI tools then this can be ignored." >> $GITHUB_STEP_SUMMARY
            fi