name: Linting (optional)

on:
  workflow_call:

jobs:
  terraform:
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Work In Progress
        shell: bash
        run: |
          echo "This lint workflow is a WIP for Stage-2"

  ai:
    name: AI
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Document AI usage
        shell: bash
        run: |
            FILE_AI="AI.md"
            if [ -f "$FILE_AI" ]; then
              echo "AI Declaration:" >> $GITHUB_STEP_SUMMARY
              cat "$FILE_AI" >> $GITHUB_STEP_SUMMARY
            else 
              echo "> [!IMPORTANT]" >> $GITHUB_STEP_SUMMARY
              echo "> No AI usage declared or declaration is missing." >> $GITHUB_STEP_SUMMARY
            fi