name: Linting (optional)

on:
  workflow_call:

jobs:
  terraform:
    runs-on: [self-hosted, Linux, X64, amazon, generic]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Work In Progress
        shell: bash
        run: |
          echo "This lint workflow is a WIP for Stage-2"